# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec97d71ba88e68851094b5a25d4f87d16f919079e5e3a9e59ff61823cca00ec86b0080e9e2ae9351fb8edc19e34f986495ba83d80844642743bdb6b30ec32aa0

test:
  secret_key_base: 446620040b7182f232417c432095423af11fad8770667422cc139c3b438aa43c13e49ae8543d59f62b31853fb6c6161968eab73bef65b354ad1e2bc6c8915023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
